position = "Bottom"

[modules]
left = [ "Workspaces" ]
center = []
right = [ "Clock", [ "Settings" ] ]

[appearance]
font_name = "JetBrainsMono Nerd Font Mono"
scale_factor = 1.15
style = "Islands"

success_color = "{{ colors.tertiary.default.hex }}"
text_color = "{{ colors.on_surface.default.hex }}"

workspace_colors = [
  "{{ colors.primary.default.hex }}",
  "{{ colors.secondary.default.hex }}",
  "{{ colors.tertiary.default.hex }}"
]

[appearance.primary_color]
base = "{{ colors.primary.default.hex }}"
text = "{{ colors.on_primary.default.hex }}"

[appearance.danger_color]
base = "{{ colors.error.default.hex }}"
weak = "{{ colors.error_container.default.hex }}"

[appearance.background_color]
base = "{{ colors.background.default.hex }}"
weak = "{{ colors.surface_container.default.hex }}"
strong = "{{ colors.surface_container_high.default.hex }}"

[appearance.secondary_color]
base = "{{ colors.secondary.default.hex }}"
strong = "{{ colors.secondary_container.default.hex }}"

[appearance.menu]
backdrop = 0.2

[clock]
format = "%a %d %b %R"
