[config]
version_check = false
caching = false

[config.wallpaper]
set = true
command = "awww img {{ image }} --transition-type wipe"
args = []


[templates.ashell]
input_path = './ashell.toml'
output_path = '~/.config/ashell/config.toml'

[templates.dircolors]
input_path = "./dircolors"
output_path = "~/.dircolors"
post_hook = "eval $(dircolors ~/.dircolors)"

[templates.emacs]
input_path = "./emacs.el"
output_path = "~/.emacs.d/matugen.el"
post_hook = "emacsclient -e '(load \"~/.emacs.d/matugen.el\")'"

[templates.ghostty]
input_path = './ghostty'
output_path = '~/.config/ghostty/themes/Matugen'
post_hook = 'pkill -SIGUSR2 ghostty'

[templates.hyprland]
input_path = './hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'

[templates.mako]
input_path = './mako'
output_path = '~/.config/mako/mako-colors'
post_hook = 'makoctl reload'

[templates.ps1]
input_path = "./bash_ps1.sh"
output_path = "~/.bash_ps1.sh"
post_hook = "source ~/.bash_ps1.sh"
